### ISSUE TITLE
Icon for SVG file

### ISSUE THREAD

**Issue by tiborepcek** [splitbrain/file-icon-generator#1]
Hi.

As i wrote in forum (https://forum.dokuwiki.org/post/64438), i need a new icon for SVG file.

Can i help somehow?

Thanks.

edit: I managed to draw 16x16 and 32x32 png icons for svg files thanks to file icon generator. I also added these png files to lib/images/fileicons and lib/images/fileicons/32x32. And how can i now show that icons?

**Comment by splitbrain** [comment]
this should be a issue in DokuWiki not the file icon generator
